### ISSUE TITLE
traceback incomplete

### ISSUE THREAD

**Issue by martin-raden** [drdrsh/Needleman-Wunsch#2]
The implementation present on [http://experiments.mostafa.io/public/needleman-wunsch/](http://experiments.mostafa.io/public/needleman-wunsch/) shows an incomplete traceback and alignment score.

e.g. try

seq1 CACCGG
seq2 AACACC
match 0
mismatch -1
gap -1

the output alignment

C	A	C	C	-	-
C	A	C	C	G	G

misses the leading "AA" from seq2

and reports a score of 2 (which is correct for the subalignment shown), while the DP matrix gives a global score of 0.

I guess, your traceback stops once it reaches row/col 0 and does not do the traceback to cell (0,0) as expected..

anyway, thanks a lot for the implementation! :)

**Comment by drdrsh** [comment]
Took my time but I fixed that in 68f9b8b4c08975ce22f7c8e3e8c5e8c5308bebe1.

And yes, you are correct, I was stopping when either x or y is 0.

Thanks for reporting.
